version: '3.8'

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "keycloak" ]
      start_period: 30s
      interval: 10s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - "8081:8080"
    volumes:
      - ./realm.json:/opt/jboss/keycloak/realm.json
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm.json"
    healthcheck:
      test: "curl -f http://localhost:8080/auth || exit 1"
      start_period: 30s
    depends_on:
      - postgres

  mongodb:
    image: mongo:5.0.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: "echo 'db.stats().ok' | mongo localhost:27017/spring-demo --quiet"
